version: "3"
services:
  docs:
    container_name: docs
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/html:/usr/share/nginx/html:ro"

  redis:
    container_name: redis
    image: redis
    restart: always

  mysql:
      container_name: mysql
      restart: always
      image: mysql/mysql-server:latest
      ports:
        - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: Whoisonscreen_Root!
        MYSQL_USER: WIOS_User
        MYSQL_PASSWORD: Whoisonscreen!
        MYSQL_DATABASE: facial_db
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      volumes:
        - ./facial_database/sql_data/db:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: WIOS_User
      PMA_PASSWORD: Whoisonscreen!
    ports:
      - "8080:80"

  postgres-airflow:
    container_name: postgres-airflow
    image: postgres:11
    restart: always
    volumes:
      - postgres-airflow-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    ports:
      - "5434:5432"

  airflow:
    container_name: airflow
    image: puckel/docker-airflow
    restart: always
    depends_on:
      - postgres-airflow
    environment:
      EXECUTOR: Local
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 9090
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: "Eff80poJxv6LE4432pDC6OmD6N449KCSuhUAMLXiq4U="
    ports:
      - "9090:9090"
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
      - ./facial_database:/usr/local/facial_database
volumes:
  postgres-airflow-data:

